```
└── 📁Devido
    └── 📁client
        └── 📁.firebase
            ├── hosting.cHVibGlj.cache
        └── 📁.vercel
            ├── project.json
            ├── README.txt
        └── 📁public
            ├── 404.html
            ├── favicon.ico
            ├── favicon1.png
            ├── index.html
            ├── logo192.png
            ├── logo512.png
            ├── manifest.json
            ├── robots.txt
        └── 📁src
            └── 📁components
                ├── Card.jsx
                ├── Comment.jsx
                ├── Comments.jsx
                ├── Menu.jsx
                ├── Navbar.jsx
                ├── Recomendations.jsx
                ├── Upload.jsx
            └── 📁firebase
                ├── firebase.js
            └── 📁images
                ├── Dummy.jpg
                ├── Dummy2.jpg
                ├── logo.png
            └── 📁pages
                ├── Home.jsx
                ├── Profile.jsx
                ├── Search.jsx
                ├── SignIn.jsx
                ├── Video.jsx
            └── 📁redux
                ├── store.js
                ├── userSlice.js
                ├── videoSlice.js
            └── 📁utils
                ├── Theme.js
            ├── .env
            ├── App.js
            ├── App.test.js
            ├── index.css
            ├── index.js
            ├── logo.svg
            ├── reportWebVitals.js
            ├── setupTests.js
        ├── .firebaserc
        ├── .gitignore
        ├── cors.json
        ├── firebase.json
        ├── package-lock.json
        ├── package.json
        ├── storage.rules
    └── 📁server
        └── 📁.vercel
            ├── project.json
            ├── README.txt
        └── 📁controllers
            ├── Auth.js
            ├── Comment.js
            ├── User.js
            ├── Video.js
        └── 📁error
            ├── error.js
        └── 📁middlewares
            ├── verifyUser.js
        └── 📁models
            ├── Comments.js
            ├── User.js
            ├── Video.js
        └── 📁routes
            ├── Auth.js
            ├── Comment.js
            ├── User.js
            ├── Video.js
        ├── .env
        ├── .gitignore
        ├── db.js
        ├── index.js
        ├── package-lock.json
        ├── package.json
        ├── vercel.json
    ├── .gitignore
    ├── README.md
    └── Struct.lua
```